// Copy from the live site, 20 Sep 2026. Two answers ("food and drinks available" / "vegetarian options") were swapped on the live site; corrected here.
export const FAQS: [string, string][] = [
  ["Can I buy tickets at the venue?", "Yes, but we strongly recommend purchasing your ticket online in advance to avoid delays at the gate. Online purchase is faster and guarantees your access."],
  ["Is re-entry allowed if I leave and come back?", "Yes, re-entry is allowed, but only if:<br>• You have a valid festival wristband securely on your wrist (not damaged or removed).<br>• You go through the security re-check at the entrance when returning.<br><br>Please note that if your wristband is missing, tampered with, or transferred to someone else, you will not be allowed back into the venue. We recommend you plan ahead and avoid unnecessary movement in and out so you can make the most of your festival experience."],
  ["What items are not allowed into the festival venue?", "To keep everyone safe and ensure a smooth event, the following items are not allowed:<br>• Sharp objects, knives, or any weapon<br>• Guns or any form of firearm (even if licensed)<br>• Outside food or drinks<br>• Glass bottles or breakable containers<br>• Hard drugs or illegal substances<br>• Large umbrellas, drones, fireworks, or laser pointers<br><br>All bags will be checked at the entrance, so please travel light and stay safe."],
  ["Will there be food and drinks available to buy at the event?", "Yes, there will be plenty of food and drinks available throughout the event. It’s a food festival, so expect a wide variety of African and Nigerian dishes — from street food favorites to traditional meals, grills, small chops, and local delicacies you may not easily find every day. There will also be refreshing drinks, cocktails, and beverages to pair with your meals. Come hungry and ready to explore."],
  ["Are there vegetarian, vegan, or gluten-free options?", "While we’re actively working with our food vendors to include more vegetarian, vegan, and gluten-free options, these may be limited at the moment. We’ll share updates on available food options closer to the event, and we’re committed to making the festival inclusive for everyone in the future."],
  ["Can I bring my kids or come with my family?", "Yes, kids are allowed and kids under the age of 13 are allowed to enter for free. Kids above 13 are supposed to get the ticket."],
  ["Will there be music and entertainment alongside the food activities?", "Yes, there’s going to be a lot of live performances and creative performances, both dancing and all of that. There’s going to be a masquerade parade. You’re going to feel the entirety of African culture, of Nigerian culture."],
  ["Is there parking available at the venue?", "Parking is only available for VVIP table reservations, official vendors, team members, sponsors, and partners. If you’re attending as a regular guest, we strongly advise you to use ride-hailing services (like Bolt or Uber) or public transportation to avoid any inconvenience. There will be no general parking available on-site."],
  ["Will alcohol be sold at the festival?", "Yes, alcohol will be sold at the festival, but strictly to guests aged 18 and above."],
  ["What forms of payment are accepted?", "You can use cash, POS, or bank transfer to purchase food, drinks, and other items from vendors at the festival.<br><br>However, if you’re buying a ticket at the ticketing stand, payment is strictly by POS or bank transfer only — cash will not be accepted."],
  ["Will there be a list of participating food vendors?", "Yes, there’s a list of vendors participating on the website, and their menu will also be provided for accessibility before the day of the event."],
  ["Are there VIP or premium tickets?", "Yes, there are VIP and premium tickets, and you can click on the VIP section of the ticket to get access."],
  ["Can I bring my camera or professional equipment?", "Only registered media personnel are allowed to bring professional equipment to the event. Only phone cameras/mobile devices are allowed at the event without a media pass.<br><br>Click <a href=\"/contact\" class=\"underline\">here</a> to get media accreditation for the event."],
  ["Is the venue accessible for people with disabilities?", "Yes, the venue is accessible to people with disabilities."],
  ["Will there be security and first aid on-site?", "Yes. The festival will have professional security personnel throughout the venue, along with a fully equipped medical team on standby. Your safety and wellbeing are our top priority."],
  ["Can I volunteer to be part of the festival team?", "Yes, you can register to be a volunteer or content creator. There’s a registration form available through the volunteer link provided.<br><br>Register as a <a href=\"/contact\" class=\"underline\">Volunteer</a> / <a href=\"/contact\" class=\"underline\">Content Creator</a>."],
];
