import type { Metadata } from "next";
import CityPage from "@/components/CityPage";
export const metadata: Metadata = { title: "Abuja Festival 2025", description: "AFDF Abuja 2025, 16th November, Harrow Park, Abuja, Nigeria." };
export default function Abuja() {
  return <CityPage city="Abuja" dateLine="16th November" venue="Harrow Park, Abuja, Nigeria" month="November" hero="02-Featured-Image-Abuja-1.jpg" video={["AertRzIP_nE", "Taste Africa at the 2024 African Food and Drinks Festival in Abuja, Nigeria!"]} ticketHref="/register"
    join="The 5th edition of the African Food & Drinks Festival takes over Harrow Park for a full day of food, music, culture, and celebration, uniting thousands of Africans and the diaspora through unforgettable shared experiences."
    extras={[["Food Tour & Cultural Night", "The AFDF 2025 “United by Food” Tour is a one-day premium culinary journey across Africa’s diverse regions — East, North, Central, Southern, and West Africa — culminating in a grand finale cultural night in Nigeria. Expect authentic tastings, chef talks, music, dance, storytelling, and a once-in-a-lifetime Pan-African experience."], ["African Food Summit & Expo", "The African Food Summit & Expo 2025 aims to deliver a high-impact, in-person event on November 14, 2025, at the Musa Yar'Adua Center in Abuja, Nigeria. The summit's theme, \"United by Food,\" will bring together policymakers, agro-entrepreneurs, chefs, tech innovators, diaspora leaders, and media professionals."]]}
    recapTitle="How It Went In" recapYear="2024" recapBody="On November 15th, 2024, the grandest food festival to date captivated over six thousand attendees at Tobix Garden in Abuja. The festival was a vibrant and immersive celebration of African culture, bringing together family and friends to savor an array of Afro-themed food stands and delightful local vendors. This spectacular event showcased the richness of flavors, diverse cultures, and culinary traditions across the African continent, making it an unforgettable experience for all who attended." />;
}
